[package]
name = "solution"
version = "0.1.0"
authors = ["MathuxNY-73 <pouillaude.a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
input = { path = "../../library/rust/input" }
