[package]
name = "solution"
version = "0.1.0"
authors = ["MathuxNY-73 <pouillaude.a@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.7"
input = { path = "../../library/rust/input" }
