[package]
name = "solution"
version = "0.1.0"
authors = ["MathuxNY-73 <pouillaude.a@gmail.com>"]
edition = "2018"

[lib]
name = "myio"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"